name: "Collate changed files"
on:
  push:
    branches: [3.*, 4.*, main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  changed-files:
    runs-on: ubuntu-latest
    steps:
      - name: Filter Files
        id: filter-files
        uses: dorny/paths-filter@v3
        with:
          filters: |
            check_build:
              - '**.go'
              - 'go.mod'
              - '.github/workflows/build.yml'
              - 'scripts/dqlite/**'
              - 'Makefile'
              - 'make_functions.sh'
            check_client:
              - '**.go'
              - 'go.mod'
              - '.github/workflows/client-tests.yml'
              - 'scripts/dqlite/**'
              - 'Makefile'
              - 'make_functions.sh'
            check_migrate:
              - '**.go'
              - 'go.mod'
              - 'snap/**'
              - '.github/workflows/migrate.yml'
              - 'scripts/dqlite/**'
              - 'Makefile'
              - 'make_functions.sh'
            check_upgrade:
              - '**.go'
              - 'go.mod'
              - 'snap/**'
              - '.github/workflows/migrate.yml'
              - 'scripts/dqlite/**'
              - 'Makefile'
              - 'make_functions.sh'
            check_snap:
              - '**.go'
              - 'go.mod'
              - 'snap/**'
              - '.github/workflows/snap.yml'
              - 'scripts/dqlite/**'
              - 'Makefile'
              - 'make_functions.sh'
            check_terraform:
              - '**.go'
              - 'go.mod'
              - '.github/workflows/terraform-smoke.yml'
            check_generate:
              - '**.go'
              - 'go.mod'
              - '.github/workflows/gen.yml'

      - name: Set Flags
        id: set-flags
        run: |
          printf '{ 
            "check-build": ${{ steps.collate-files.outputs.check_build }},  
            "check-client": ${{ steps.collate-files.outputs.check_client }},  
            "check-migrate": ${{ steps.collate-files.outputs.check_migrate }},  
            "check-upgrade": ${{ steps.collate-files.outputs.check_upgrade }},  
            "check-snap": ${{ steps.collate-files.outputs.check_snap }},  
            "check-terraform": ${{ steps.collate-files.outputs.check_terraform }},  
            "check-generate": ${{ steps.collate-files.outputs.check_generate }},  
          }' >> check-flags.json
      - uses: actions/upload-artifact@v4
        with:
          name: check-flags
          path: check-flags.json
          compression-level: 0
          retention-days: 1
