name: "CLA check"
on: [pull_request, workflow_dispatch]
permissions:
  contents: read

jobs:
  cla-check:
    permissions:
      pull-requests: write  # for canonical/has-signed-canonical-cla to create & update comments
    runs-on: ubuntu-latest
    steps:
      - name: Check if CLA signed
        uses: canonical/has-signed-canonical-cla@9a7e0da38a13dbc25b14c389851bcf1624f4784d # v1
        with:
          accept-existing-contributors: true
